### ISSUE TITLE
How to extract the video features with CLIP visual encoder?

### ISSUE THREAD

**Issue by jianhua2022** [sauradip/STALE#13]
Thanks for your great work! I have a question about how to extract video features by using CLIP visual encoder in your work, since I want to extract video features with CLIP visual encoder in a new dataset. If I3D or C3D is used as a video encoder, a video clip with 16 or 32 frames is represented as a feature vector. While for CLIP visual encoder, whether it is needed to extract the 16 or 32 frames features for a video clip? If that, a long video may have thousands of frame features. So, could you give me some details about CLIP features for a video?

**Comment by sauradip** [comment]
Yes , a snippet consists of 16 frames , so we pass 16 frames from video as input into the CLIP vision encoder and extract the 1-D features. Likewise for the whole video we extract all the variable sized features and then we bilinear sample fixed length temporal dimension for  fitting into our model.

**Comment by Coder-Liuu** [comment]
Thank you for your kind words. I noticed that the number of frames in the `video_info_new.csv` file does not match the actual feature size, which is confusing. For example, the video `v_--0edUL8zmA` shows 2304 frames in the file, but when I read the corresponding npy file, the size is (921, 512) instead of (2304, 512). Could you please explain this discrepancy?

Additionally, I found a configuration in the YAML file with the variable `num_frame: 5`. Do you remember what this variable represents?

**Comment by sauradip** [comment]
We did not extract any of the features hence I would recommend you to contact authors of EffPrompt (https://github.com/ju-chen/Efficient-Prompt) who provided us with the features.
