### ISSUE TITLE
Why use only the last segment of the video

### ISSUE THREAD

**Issue by Coder-Liuu** [sauradip/STALE#24]
In file `STALE/stale_lib/stale_dataloader.py` , I noticed that the following code means, for a video, to add all the segments from the corresponding annotation file into the label_list.
```python
for j in range(len(labels)):
    tmp_info = labels[j]
    clip_factor = self.temporal_scale / ( corr_sec * (self.num_frame+1) )
    action_start = tmp_info['segment'][0]*clip_factor
    snip_start = max(min(1, tmp_info['segment'][0] / corr_sec), 0)
    action_end = tmp_info['segment'][1]*clip_factor
    snip_end = max(min(1, tmp_info['segment'][1] / corr_sec), 0)
    gt_label = tmp_info["label"]

if action_end - action_start > 1 and gt_label in lbl_dict:
    label_list.append([snip_start,snip_end,gt_label])
```
But this code actually adds only the last segment. Is the following code correct? 
```python
for j in range(len(labels)):
    tmp_info = labels[j]
    clip_factor = self.temporal_scale / ( corr_sec * (self.num_frame+1) )
    action_start = tmp_info['segment'][0]*clip_factor
    snip_start = max(min(1, tmp_info['segment'][0] / corr_sec), 0)
    action_end = tmp_info['segment'][1]*clip_factor
    snip_end = max(min(1, tmp_info['segment'][1] / corr_sec), 0)
    gt_label = tmp_info["label"]

    if action_end - action_start > 1 and gt_label in lbl_dict:
        label_list.append([snip_start,snip_end,gt_label])
```

I would greatly appreciate it if you could spare some time to answer my question despite your busy schedule.

**Comment by sauradip** [comment]
This code snippet does not add 'any' segments to the label_list. It adds the foreground actions into the label_list. Your question is perhaps why only last foreground segment ! In our experiments we saw for activitynet, there are only a handful of videos where we have multi-segments. One of the drawback of our approach is that the 2nd segment onwards does not get predicted well (as we dont predict start/end regressors) and drops the avg mAP. In THUMOS, this is not the case. Hence your code snippet is correct for THUMOS dataloader. Because there are a lot of short actions and missing one / only selecting last will have impact on the approach.

**Comment by Coder-Liuu** [comment]
Thank you very much for your reply. Is it unfair to calculate the mAP if only the last foreground segment is used as the label? Because the video actually has multiple foreground segments.

**Comment by sauradip** [comment]
In this case we are actually underutilizing the mAP metric. I did not have time to tune the hyper parameters to check all the segments. But I vividly remember that I need to increase the per snippet duration in the 1D mask to allocate all the segments. That means I am effectively consuming background frames within a foreground which drops the performance further.

**Comment by Coder-Liuu** [comment]
Thanks for the reply, I see.
